name: Release

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '22.x'

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - name: Install dependencies
        run: npm ci

      - name: Release it
        run: npm run release:ci
        env:
          GITHUB_TOKEN_CUSTOM: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
